apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-frontend
        image: [INSERT IMAGE NAME]
        ports:
        - containerPort: 3000